// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfl1k9orUce0L5-44N_bUiAJhsX0CWZsE',
    appId: '1:134210311124:web:1a34f055680ecef592fc41',
    messagingSenderId: '134210311124',
    projectId: 'smusicrocks-e9686',
    authDomain: 'smusicrocks-e9686.firebaseapp.com',
    storageBucket: 'smusicrocks-e9686.firebasestorage.app',
    measurementId: 'G-RY8DZXXWCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSrITCv-L6DciUYVM_3xXeT5R9gjf8paI',
    appId: '1:134210311124:android:3a3a6a91f0263d5292fc41',
    messagingSenderId: '134210311124',
    projectId: 'smusicrocks-e9686',
    storageBucket: 'smusicrocks-e9686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9RCHgGarUNBedPJGdJoVT9rRV7kMmCRs',
    appId: '1:134210311124:ios:02dfe2d2dc2c81d492fc41',
    messagingSenderId: '134210311124',
    projectId: 'smusicrocks-e9686',
    storageBucket: 'smusicrocks-e9686.firebasestorage.app',
    iosBundleId: 'com.example.srockMusicServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9RCHgGarUNBedPJGdJoVT9rRV7kMmCRs',
    appId: '1:134210311124:ios:02dfe2d2dc2c81d492fc41',
    messagingSenderId: '134210311124',
    projectId: 'smusicrocks-e9686',
    storageBucket: 'smusicrocks-e9686.firebasestorage.app',
    iosBundleId: 'com.example.srockMusicServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfl1k9orUce0L5-44N_bUiAJhsX0CWZsE',
    appId: '1:134210311124:web:eb32abcfcee73a9292fc41',
    messagingSenderId: '134210311124',
    projectId: 'smusicrocks-e9686',
    authDomain: 'smusicrocks-e9686.firebaseapp.com',
    storageBucket: 'smusicrocks-e9686.firebasestorage.app',
    measurementId: 'G-5XY182BG27',
  );

}